version: '3'

services:
  nginx-master:
    container_name: camera-nginx-master
    restart: always
    image: nginx
    ports:
      - "8800:80"
    links:
      - nginx-backend-one
      - nginx-backend-two
    volumes:
      - ./nginx-conf/master:/etc/nginx/conf.d

  workspace-one:
    container_name: camera-workspace-one
    restart: always
    image: dinhtai/laravel-workspace
    volumes:
      - ./camera1:/var/www/laravel
    tty: true
  php-fpm-one:
    container_name: camera-php-fpm-one
    restart: always
    image: dinhtai/laravel-php-fpm
    volumes:
      - ./camera1:/var/www/laravel
    expose:
      - "9000"
  nginx-backend-one:
    container_name: camera-nginx-backend-one
    restart: always
    image: dinhtai/laravel-nginx
    volumes:
      - ./nginx-conf/backend-1:/etc/nginx/conf.d
      - ./camera1:/var/www/laravel
    ports:
      - "1111:80"
    links:
      - php-fpm-one

  workspace-two:
    container_name: camera-workspace-two
    restart: always
    image: dinhtai/laravel-workspace
    volumes:
      - ./camera2:/var/www/laravel
    tty: true
  php-fpm-two:
    container_name: camera-php-fpm-two
    restart: always
    image: dinhtai/laravel-php-fpm
    volumes:
      - ./camera2:/var/www/laravel
    expose:
      - "9000"
  nginx-backend-two:
    container_name: camera-nginx-backend-two
    restart: always
    image: dinhtai/laravel-nginx
    volumes:
      - ./nginx-conf/backend-2:/etc/nginx/conf.d
      - ./camera2:/var/www/laravel
    ports:
      - "2222:80"
    links:
      - php-fpm-two
  mysql:
    container_name: camera-mysql
    restart: always
    image: mysql:5.7
    volumes:
      - .docker/mysql:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: camera
      MYSQL_USER: camera
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  redis:
    container_name: camera-redis
    restart: always
    image: redis
    expose:
      - "6379"
    volumes:
      - .docker/redis:/data
